package in.ineuron.model;
// Generated Jan 3, 2025, 1:03:04 AM by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Insurancepolicy generated by hbm2java
 */
@Entity
@Table(name = "insurancepolicy", catalog = "student")
public class Insurancepolicy implements java.io.Serializable {

	private long pid;
	private String pname;
	private String ptype;
	private Integer tenure;
	private String compny;
	private Integer count;

	public Insurancepolicy() {
	}

	public Insurancepolicy(long pid) {
		this.pid = pid;
	}

	public Insurancepolicy(long pid, String pname, String ptype, Integer tenure, String compny, Integer count) {
		this.pid = pid;
		this.pname = pname;
		this.ptype = ptype;
		this.tenure = tenure;
		this.compny = compny;
		this.count = count;
	}

	@Id

	@Column(name = "pid", unique = true, nullable = false)
	public long getPid() {
		return this.pid;
	}

	public void setPid(long pid) {
		this.pid = pid;
	}

	@Column(name = "pname")
	public String getPname() {
		return this.pname;
	}

	public void setPname(String pname) {
		this.pname = pname;
	}

	@Column(name = "ptype")
	public String getPtype() {
		return this.ptype;
	}

	public void setPtype(String ptype) {
		this.ptype = ptype;
	}

	@Column(name = "tenure")
	public Integer getTenure() {
		return this.tenure;
	}

	public void setTenure(Integer tenure) {
		this.tenure = tenure;
	}

	@Column(name = "compny", length = 45)
	public String getCompny() {
		return this.compny;
	}

	public void setCompny(String compny) {
		this.compny = compny;
	}

	@Column(name = "count")
	public Integer getCount() {
		return this.count;
	}

	public void setCount(Integer count) {
		this.count = count;
	}

	@Override
	public String toString() {
		return "Insurancepolicy [pid=" + pid + ", pname=" + pname + ", ptype=" + ptype + ", tenure=" + tenure
				+ ", compny=" + compny + ", count=" + count + "]";
	}

}
